name: Deploy to HTTPD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker.io
      
    - name: Build Docker image
      run: |
        docker build -t my-web-app .
      
    - name: Tag Docker image
      run: |
        docker tag my-web-app:latest my-docker-username/my-web-app:latest
        
    - name: Push Docker image to registry
      run: |
        docker login -u my-docker-username -p ${{ secrets.DOCKER_PASSWORD }}
        docker push my-docker-username/my-web-app:latest
      
    - name: Deploy Docker image to HTTPD
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          sudo docker stop my-web-app || true
          sudo docker rm my-web-app || true
          sudo docker pull my-docker-username/my-web-app:latest
          sudo docker run -d --name my-web-app -p 80:80 my-docker-username/my-web-app:latest
